# Generated by Django 6.0.3 on 2026-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('rede', 'Rede'), ('acesso', 'Acesso'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
